#!/bin/bash
# config file for BSSM
# enable options with 1, disable them with 0 (or basically anything else)

# Output directory and file name. Make sure the directory is actually existent and writeable by the user you run this as.
# If HTML output is activated, the appropiate extension needs to be added manually.
OUTPUT_DIR=.
OUTPUT_FILENAME=bssm_output

# Turn on archiving of older stats.
ARCHIVE=0

# This string is used to optically separate the different segments.
FIELD_SEPARATOR="=========="

# Individual modules can be switched off and on here
MOD_HEADER=1
MOD_HTML=1          # output a HTML file instead of plain text; foreground and background colors can be configured below
MOD_HTML_COLOR=#00FF00
MOD_HTML_BACKGROUND=black
MOD_CPU=1
MOD_SENSORS=1
MOD_SYSINFO=1
MOD_FILESYSTEMS=1
MOD_RAM=1
MOD_TASKS=1
MOD_TASKS_COUNT=10  # Number of top tasks to display. Has to be an integer obviously.
MOD_NETWORK=1
MOD_NETWORK_DEVICE= # Set this to the network device for which you want statistics, or leave empty to show all.
MOD_NETWORK2=0      # The same as before, in case one wants to monitor a second, specific network device
MOD_NETWORK_DEVICE2=
MOD_FOOTER=1
